-- Создание таблицы пользователей
CREATE TABLE users
(
    id                              INT                 NOT NULL    GENERATED BY DEFAULT AS IDENTITY(MINVALUE 0 START WITH 0 INCREMENT BY 1),
    username                        VARCHAR(180)        NOT NULL,
    password                        VARCHAR(180)        NOT NULL,
    token                           VARCHAR(362),
    roles                           JSON,
    registration_timestamp          TIMESTAMP           NOT NULL    DEFAULT NOW(),
    CONSTRAINT pkey_users_id        PRIMARY KEY(id),
    CONSTRAINT ukey_users_login     UNIQUE(username),
    CONSTRAINT ukey_users_token     UNIQUE(token)
);