CREATE TABLE users
(
	id				        INT		        NOT NULL	GENERATED BY DEFAULT AS IDENTITY(MINVALUE 0 START WITH 0 INCREMENT BY 1),
	login				    VARCHAR(32)	    NOT NULL,
	password_sha512		    VARCHAR(128)	NOT NULL,
	registration_timestamp	TIMESTAMP	    NOT NULL	DEFAULT NOW(),
	CONSTRAINT users_id		PRIMARY KEY(id),
	CONSTRAINT users_login	UNIQUE(login)
);