version: '3.7'

volumes:
  php-var:
    name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.volume.php-var
  php-vendor:
    name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.volume.php-vendor

networks:
  inner-network:
    name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}/network

services:
  php:
    build:
      args:
        - APP_ROOT=${APP_ROOT}
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-working_with_resumes}/image/php:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.container.php
    volumes:
      - .:${APP_ROOT}
      - ./config/ini/php.ini:/usr/local/etc/php/php.ini
      - ./config/ini/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - php-var:${APP_ROOT}/var
      - php-vendor:${APP_ROOT}/vendor
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - inner-network

  nginx:
    image: nginx:1.23.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.container.nginx
    hostname: working_with_resumes
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    networks:
      - inner-network
    depends_on:
      - php
    ports:
      - ${APP_PORT}:80

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-working_with_resumes}/image/postgres:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.container.postgres
    environment:
      - POSTGRES_HOST=${DBMS_HOST}
      - POSTGRES_PORT=${DBMS_PORT}
      - POSTGRES_USER=${DBMS_USER_NAME}
      - POSTGRES_PASSWORD=${DBMS_USER_PASSWORD}
      - POSTGRES_DB=${DBMS_DB_NAME}
    volumes:
      - ./postgres/sql-scripts:/var/lib/postgresql/sql-scripts
      - ${POSTGRES_DATA_LOCAL_PATH:-./postgres/data}:/var/lib/postgresql/data
    networks:
      - inner-network
    ports:
      - ${DBMS_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:6.12
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DBMS_GUI_USER_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DBMS_GUI_USER_PASSWORD}
    container_name: ${COMPOSE_PROJECT_NAME:-working_with_resumes}.container.pgadmin
    volumes:
      - ${PGADMIN_DATA_LOCAL_PATH:-./pgadmin/data}:/var/lib/pgadmin
    networks:
      - inner-network
    depends_on:
      - postgres
    ports:
      - ${DBMS_GUI_PORT}:80
