
ALTER TABLE vacancies ALTER COLUMN id RESTART SET START 12;

INSERT INTO vacancies(parent_id, id, name) VALUES (0, 1,   'Медицина');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Биохимик');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Врач-лаборант');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Врач общей практики');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Врач скорой помощи');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Военный врач');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Диетолог');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'ЛОР');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Нарколог');
INSERT INTO vacancies(parent_id, id, name) VALUES (1, 2,       'Невролог');
INSERT INTO vacancies(parent_id, name)     VALUES (2,              'Нейропсихолог');
INSERT INTO vacancies(parent_id, name)     VALUES (2,              'Нейротравматолог');
INSERT INTO vacancies(parent_id, name)     VALUES (2,              'Нейрохирург');
INSERT INTO vacancies(parent_id, id, name) VALUES (1, 3,       'Онколог');
INSERT INTO vacancies(parent_id, name)     VALUES (3,              'Онкогематолог');
INSERT INTO vacancies(parent_id, name)     VALUES (3,              'Онкогинеколог');
INSERT INTO vacancies(parent_id, name)     VALUES (3,              'Онкодерматолог');
INSERT INTO vacancies(parent_id, name)     VALUES (3,              'Онкоуролог');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Педиатр');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Санитарный врач');
INSERT INTO vacancies(parent_id, name)     VALUES (1,          'Хирург');
INSERT INTO vacancies(parent_id, id, name) VALUES (0, 4,   'Недвижимость');
INSERT INTO vacancies(parent_id, name)     VALUES (4,          'Агент по недвижимости');
INSERT INTO vacancies(parent_id, name)     VALUES (4,          'Риэлтор');
INSERT INTO vacancies(parent_id, id, name) VALUES (0, 5,   'Преподавание и языки');
INSERT INTO vacancies(parent_id, name)     VALUES (5,          'Методист');
INSERT INTO vacancies(parent_id, name)     VALUES (5,          'Преподаватель');
INSERT INTO vacancies(parent_id, name)     VALUES (5,          'Социальный педагог');
INSERT INTO vacancies(parent_id, name)     VALUES (5,          'Лингвист');
INSERT INTO vacancies(parent_id, name)     VALUES (5,          'Русист');
INSERT INTO vacancies(parent_id, id, name) VALUES (0, 6,   'Экономика, бизнес, страхование');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Администратор');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Аудитор');
INSERT INTO vacancies(parent_id, id, name) VALUES (6, 7,       'Безопасность');
INSERT INTO vacancies(parent_id, name)     VALUES (7,              'Инженер по охране труда');
INSERT INTO vacancies(parent_id, name)     VALUES (7,              'Пожарный инспектор');
INSERT INTO vacancies(parent_id, name)     VALUES (7,              'Инженер по пожарной безопасности');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Бухгалтер');
INSERT INTO vacancies(parent_id, id, name) VALUES (6, 8,       'Директора и руководители');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Генеральный директор');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Директор по маркетингу');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Директор по производству');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Директор по развитию');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Исполнительный директор');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Технический директор');
INSERT INTO vacancies(parent_id, name)     VALUES (8,              'Финансовый директор');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Инкассатор');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Кассир');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Маркетолог');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Метролог');
INSERT INTO vacancies(parent_id, name)     VALUES (6,          'Промоутер');
INSERT INTO vacancies(parent_id, id, name) VALUES (6, 9,       'Секретариат и делопроизводство');
INSERT INTO vacancies(parent_id, name)     VALUES (9,              'Архивариус');
INSERT INTO vacancies(parent_id, name)     VALUES (9,              'Делопроизводитель');
INSERT INTO vacancies(parent_id, name)     VALUES (9,              'Офис-менеджер');
INSERT INTO vacancies(parent_id, name)     VALUES (9,              'Секретарь');
INSERT INTO vacancies(parent_id, id, name) VALUES (6, 10,      'Страхование');
INSERT INTO vacancies(parent_id, name)     VALUES (10,             'Актуарий');
INSERT INTO vacancies(parent_id, name)     VALUES (10,             'Андеррайтер');
INSERT INTO vacancies(parent_id, name)     VALUES (10,             'Страховой агент');
INSERT INTO vacancies(parent_id, id, name) VALUES (0, 11,  'Юриспруденция');
INSERT INTO vacancies(parent_id, name)     VALUES (11,         'Адвокат');
INSERT INTO vacancies(parent_id, name)     VALUES (11,         'Нотариус');
INSERT INTO vacancies(parent_id, name)     VALUES (11,         'Судебный эксперт');
INSERT INTO vacancies(parent_id, name)     VALUES (11,         'Юрисконсульт');
INSERT INTO vacancies(parent_id, name)     VALUES (11,         'Юрист');